---
tags:
  - base
---

```cpp
double& Vector::operator[](int i) {
	if (i < 0 || i >= size()) {
		throw out_of_range{"Vector::operator[]"};
	}
	return elem_[i];
} 
```

Инструкция `throw` передает управление обработчику исключений типа `out_of_range` в некоторой [[Функции]], которая вызывает `Vector::operator[]()` 

```cpp
void f(Vector& v) {
	//...
	try {
		v[v.size()] = 7;
	} catch (out_of_range& err) {
		cerr << err.what() << endl;
	}
	//...
}
```

Мы помещаем код, в обработке исключений в котором мы заинтересованы, в блок `try`. Попытка `v[v.size()]` выходит за границы, поэтому управление будет передано в блок `catch`.

[[Функции|Функция]], которая не должна генерировать исключения, будет объявлена с флагом [[noexcept|noexcept]].

> [!tip]
> - Генерируйте исключения для указания того, что вы не в состоянии выполнить определенную задачу
> - Используйте исключение только для [[Обработка ошибок|обработки ошибок]]
> - Используйте для исключений специально разработанные пользовательские типы (не встроенные типы)
> - Не пытайтесь перехватить все исключения в каждой [[Функции]]

[[!Язык программирования C++. Краткий курс|Источник]]
